paths:
  /products:
    get:
      tags:
        - Products
      summary: Buscar produtos
      description: Retorna uma lista contendo varios produtos
      responses:
        '200':
          description: Uma lista de Produtos
          schema:
            $ref: '#/definitions/Products'
    post:
      tags:
        - Products
      summary: Salvar produtos
      description: Salvar o produto que foi enviado como objeto
      consumes: application/json
      parameters:
        - in: body
          name: body
          description: Um objeto contendo o produto
          required: true
          schema:
            $ref: '#/definitions/Products'
      responses:
        '200':
          description: Retorna o produto salvo
          schema:
            $ref: '#/definitions/Products'
  /products/{productId}:
    get:
      tags:
        - Products
      summary: Buscar um produto
      description: Retorna um objeto contendo produto
      parameters:
      - in: path
        name: productId
        description: Produto id
        required: true
        schema:
          type: object
          properties:
            type: object
            properties:
              id:
                type: string
      responses:
        '200':
          description: Um objeto de Produtos
          schema:
            $ref: '#/definitions/Products'
    patch:
      tags:
        - Products
      summary: Alterar um produto
      description: Altera um produto pelo objeto repassado
      consumes: application/json
      parameters:
        - in: path
          name: productId
          description: Produto id
          required: true
          schema:
            type: object
            properties:
              type: object
              properties:
                id:
                  type: string
        - in: body
          name: body
          description: Um objeto de produto alterado.
          schema:
            $ref: '#/definitions/Products'
      responses:
        '200':
          description: Um objeto de Produto alterado
          schema:
            $ref: '#/definitions/Products'
    delete:
      tags:
        - Products
      summary: Deletar um produto
      description: Retorna um objeto contendo produto excluido
      parameters:
      - in: path
        name: productId
        description: Produto id
        required: true
        schema:
          type: object
          properties:
            type: object
            properties:
              id:
                type: string
      responses:
        '200':
          description: Um objeto de Produto excluido
          schema:
            $ref: '#/definitions/Products'
definitions:
  Products:
    type: object
    properties:
      name:
        type: string
      price:
        type: number
      image:
        type: string